[build]
target = [
    ".cargo/target/armv4t-nintendo-ds.json",
    ".cargo/target/armv4t-nintendo-dsi.json",
    ".cargo/target/armv5te-nintendo-ds.json",
    ".cargo/target/armv5te-nintendo-dsi.json",
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
