[package]
name = "nds_rt"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]
